"""empty message

Revision ID: 69e4c0bcd3b7
Revises: 
Create Date: 2020-04-18 02:55:27.597746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e4c0bcd3b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cast', sa.Column('movie_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cast', 'actors', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cast', type_='foreignkey')
    op.drop_column('cast', 'movie_id')
    # ### end Alembic commands ###
