"""empty message

Revision ID: 70b93a737c33
Revises: 69e4c0bcd3b7
Create Date: 2020-04-18 10:14:46.361876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b93a737c33'
down_revision = '69e4c0bcd3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cast_actor_id_fkey', 'cast', type_='foreignkey')
    op.create_foreign_key(None, 'cast', 'movies', ['actor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cast', type_='foreignkey')
    op.create_foreign_key('cast_actor_id_fkey', 'cast', 'actors', ['actor_id'], ['id'])
    # ### end Alembic commands ###
